### ISSUE TITLE
Error while loading Among us

### ISSUE THREAD

**Issue by Luckly271** [andry08/100-player-mod#3]
I get this error while loading among us with the mod :

[Error  :   BepInEx] Error loading [Player Limit Remove] : Could not resolve type with token 01000028 from typeref (expected class 'OPIJAMILNFD' in assembly 'Assembly-CSharp, Version=3.7.1.6, Culture=neutral, PublicKeyToken=null')

**Comment by andry08** [comment]
The mod at the moment is stable only in version 2020.9.22 of Among Us.
You have to install the mod on that version, you have the wrong one.
